<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Classic Black Abaya',
                'sku' => 'PRD-ABA-BLK-001',
                'description' => 'Traditional black abaya with elegant design',
                'category' => 'Abayas',
                'price' => 45.000,
                'cost' => 28.500,
                'stock_quantity' => 50,
                'reorder_level' => 15,
                'weight' => 0.650,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 20.00,
                'suggested_price' => 48.000,
                'is_active' => true,
            ],
            [
                'name' => 'Butterfly Abaya - Navy',
                'sku' => 'PRD-ABA-NAVY-002',
                'description' => 'Modern butterfly sleeve abaya in navy blue',
                'category' => 'Abayas',
                'price' => 52.000,
                'cost' => 32.000,
                'stock_quantity' => 35,
                'reorder_level' => 12,
                'weight' => 0.700,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 20.00,
                'suggested_price' => 55.000,
                'is_active' => true,
            ],
            [
                'name' => 'Embroidered Premium Abaya',
                'sku' => 'PRD-ABA-EMB-003',
                'description' => 'Luxury abaya with gold embroidery details',
                'category' => 'Abayas',
                'price' => 85.000,
                'cost' => 52.000,
                'stock_quantity' => 25,
                'reorder_level' => 8,
                'weight' => 0.750,
                'labor_cost_percentage' => 35.00,
                'overhead_cost_percentage' => 25.00,
                'suggested_price' => 88.000,
                'is_active' => true,
            ],
            [
                'name' => 'Velvet Winter Abaya - Burgundy',
                'sku' => 'PRD-ABA-VEL-004',
                'description' => 'Warm velvet abaya perfect for winter',
                'category' => 'Abayas',
                'price' => 95.000,
                'cost' => 58.000,
                'stock_quantity' => 20,
                'reorder_level' => 6,
                'weight' => 0.850,
                'labor_cost_percentage' => 32.00,
                'overhead_cost_percentage' => 22.00,
                'suggested_price' => 98.000,
                'is_active' => true,
            ],
            [
                'name' => 'Summer Chiffon Abaya - White',
                'sku' => 'PRD-ABA-CHIF-005',
                'description' => 'Light and breezy white chiffon abaya',
                'category' => 'Abayas',
                'price' => 48.000,
                'cost' => 30.000,
                'stock_quantity' => 40,
                'reorder_level' => 12,
                'weight' => 0.500,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 18.00,
                'suggested_price' => 50.000,
                'is_active' => true,
            ],
            [
                'name' => 'Open Front Cardigan Abaya',
                'sku' => 'PRD-ABA-CARD-006',
                'description' => 'Modern open front cardigan style abaya',
                'category' => 'Abayas',
                'price' => 58.000,
                'cost' => 36.000,
                'stock_quantity' => 30,
                'reorder_level' => 10,
                'weight' => 0.680,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 20.00,
                'suggested_price' => 60.000,
                'is_active' => true,
            ],
            [
                'name' => 'Crystal Embellished Evening Abaya',
                'sku' => 'PRD-ABA-CRYS-007',
                'description' => 'Elegant evening abaya with crystal details',
                'category' => 'Abayas',
                'price' => 120.000,
                'cost' => 72.000,
                'stock_quantity' => 15,
                'reorder_level' => 5,
                'weight' => 0.800,
                'labor_cost_percentage' => 35.00,
                'overhead_cost_percentage' => 25.00,
                'suggested_price' => 125.000,
                'is_active' => true,
            ],
            [
                'name' => 'Lace Trim Casual Abaya',
                'sku' => 'PRD-ABA-LACE-008',
                'description' => 'Casual abaya with delicate lace trim',
                'category' => 'Abayas',
                'price' => 55.000,
                'cost' => 34.000,
                'stock_quantity' => 28,
                'reorder_level' => 10,
                'weight' => 0.620,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 20.00,
                'suggested_price' => 57.000,
                'is_active' => true,
            ],
            [
                'name' => 'Sport Abaya - Two Piece',
                'sku' => 'PRD-ABA-SPRT-009',
                'description' => 'Comfortable two-piece sports abaya set',
                'category' => 'Abayas',
                'price' => 62.000,
                'cost' => 38.000,
                'stock_quantity' => 35,
                'reorder_level' => 12,
                'weight' => 0.720,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 20.00,
                'suggested_price' => 65.000,
                'is_active' => true,
            ],
            [
                'name' => 'Beige Linen Summer Abaya',
                'sku' => 'PRD-ABA-LIN-010',
                'description' => 'Natural beige linen abaya for hot weather',
                'category' => 'Abayas',
                'price' => 68.000,
                'cost' => 42.000,
                'stock_quantity' => 22,
                'reorder_level' => 8,
                'weight' => 0.600,
                'labor_cost_percentage' => 30.00,
                'overhead_cost_percentage' => 20.00,
                'suggested_price' => 70.000,
                'is_active' => true,
            ],
            
            // Additional product categories
            [
                'name' => 'Matching Hijab - Black',
                'sku' => 'PRD-HIJ-BLK-001',
                'description' => 'Premium black hijab to match abayas',
                'category' => 'Hijabs',
                'price' => 12.000,
                'cost' => 7.500,
                'stock_quantity' => 100,
                'reorder_level' => 30,
                'weight' => 0.150,
                'labor_cost_percentage' => 25.00,
                'overhead_cost_percentage' => 15.00,
                'suggested_price' => 13.000,
                'is_active' => true,
            ],
            [
                'name' => 'Silk Hijab - Navy',
                'sku' => 'PRD-HIJ-NAVY-002',
                'description' => 'Luxury silk hijab in navy blue',
                'category' => 'Hijabs',
                'price' => 18.000,
                'cost' => 11.000,
                'stock_quantity' => 75,
                'reorder_level' => 25,
                'weight' => 0.120,
                'labor_cost_percentage' => 28.00,
                'overhead_cost_percentage' => 18.00,
                'suggested_price' => 19.000,
                'is_active' => true,
            ],
            [
                'name' => 'Underscarves Set - 3 Pack',
                'sku' => 'PRD-UND-SET-001',
                'description' => 'Set of 3 comfortable underscarves',
                'category' => 'Accessories',
                'price' => 8.500,
                'cost' => 5.500,
                'stock_quantity' => 80,
                'reorder_level' => 20,
                'weight' => 0.200,
                'labor_cost_percentage' => 20.00,
                'overhead_cost_percentage' => 15.00,
                'suggested_price' => 9.000,
                'is_active' => true,
            ],
            [
                'name' => 'Prayer Set - Complete',
                'sku' => 'PRD-PRAY-SET-001',
                'description' => 'Complete prayer set with abaya and hijab',
                'category' => 'Prayer Sets',
                'price' => 35.000,
                'cost' => 22.000,
                'stock_quantity' => 45,
                'reorder_level' => 15,
                'weight' => 0.550,
                'labor_cost_percentage' => 28.00,
                'overhead_cost_percentage' => 18.00,
                'suggested_price' => 37.000,
                'is_active' => true,
            ],
            [
                'name' => 'Niqab - Premium Quality',
                'sku' => 'PRD-NIQ-BLK-001',
                'description' => 'High quality black niqab',
                'category' => 'Accessories',
                'price' => 15.000,
                'cost' => 9.500,
                'stock_quantity' => 60,
                'reorder_level' => 20,
                'weight' => 0.100,
                'labor_cost_percentage' => 25.00,
                'overhead_cost_percentage' => 18.00,
                'suggested_price' => 16.000,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }

        $this->command->info('✅ ' . count($products) . ' products seeded successfully!');
        $this->command->info('📊 Product breakdown:');
        $this->command->info('   - Abayas: 10');
        $this->command->info('   - Hijabs: 2');
        $this->command->info('   - Accessories: 2');
        $this->command->info('   - Prayer Sets: 1');
    }
}
