# cPanel Deployment Configuration
# Version: v1.0.0
# Description: Automatic deployment script for Huda ERP Laravel to cPanel/Hostinger
# Last Updated: 2025-01-XX

deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /bin/cp -R app $DEPLOYPATH/
    - /bin/cp -R bootstrap $DEPLOYPATH/
    - /bin/cp -R config $DEPLOYPATH/
    - /bin/cp -R database $DEPLOYPATH/
    - /bin/cp -R resources $DEPLOYPATH/
    - /bin/cp -R routes $DEPLOYPATH/
    - /bin/cp -R tests $DEPLOYPATH/
    - /bin/cp -R storage $DEPLOYPATH/
    - /bin/cp artisan $DEPLOYPATH/
    - /bin/cp composer.json $DEPLOYPATH/
    - /bin/cp composer.lock $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/
    - /bin/cp vite.config.js $DEPLOYPATH/
    - /bin/cp tailwind.config.js $DEPLOYPATH/
    - /bin/cp phpunit.xml $DEPLOYPATH/
    - /bin/cp -R public/. $DEPLOYPATH/ 2>/dev/null || /bin/cp -R public/* $DEPLOYPATH/ 2>/dev/null || true
    - cd $DEPLOYPATH
    # Fix index.php paths since everything is in public_html (replace ../ with ./)
    - sed -i "s|__DIR__\.'/\.\./|__DIR__.'/|g" index.php
    - test -f .env || cp .env.example .env 2>/dev/null || touch .env
    - sed -i 's/DB_CONNECTION=msyql/DB_CONNECTION=mysql/g' .env
    - sed -i 's/DB_CONNECTION=msql/DB_CONNECTION=mysql/g' .env
    - grep -q "APP_KEY=" .env || php artisan key:generate --force
    # Apply provided environment configuration
    - cat > .env.cpanel << 'ENVCPANEL'
APP_NAME=huda

APP_ENV=production

APP_KEY=

APP_DEBUG=true

APP_URL=https://workshop.hudaaljarallah.net

APP_LOCALE=en

APP_FALLBACK_LOCALE=en

APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file

# APP_MAINTENANCE_STORE=database

PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack

LOG_STACK=single

LOG_DEPRECATIONS_CHANNEL=null

LOG_LEVEL=debug

DB_CONNECTION=mysql

DB_HOST=127.0.0.1

DB_PORT=3306

# IMPORTANT: Update these database credentials from your cPanel MySQL section
DB_DATABASE=

DB_USERNAME=

DB_PASSWORD=

SESSION_DRIVER=database

SESSION_LIFETIME=120

SESSION_ENCRYPT=false

SESSION_PATH=/

SESSION_DOMAIN=null

BROADCAST_CONNECTION=log

FILESYSTEM_DISK=local

QUEUE_CONNECTION=database

CACHE_STORE=database

# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis

REDIS_HOST=127.0.0.1

REDIS_PASSWORD=null

REDIS_PORT=6379

MAIL_MAILER=log

MAIL_SCHEME=null

MAIL_HOST=127.0.0.1

MAIL_PORT=2525

MAIL_USERNAME=null

MAIL_PASSWORD=null

MAIL_FROM_ADDRESS="hello@example.com"

MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=

AWS_SECRET_ACCESS_KEY=

AWS_DEFAULT_REGION=us-east-1

AWS_BUCKET=

AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"
ENVCPANEL
    - for K in APP_NAME APP_ENV APP_KEY APP_DEBUG APP_URL APP_LOCALE APP_FALLBACK_LOCALE APP_FAKER_LOCALE APP_MAINTENANCE_DRIVER PHP_CLI_SERVER_WORKERS BCRYPT_ROUNDS LOG_CHANNEL LOG_STACK LOG_DEPRECATIONS_CHANNEL LOG_LEVEL DB_CONNECTION DB_HOST DB_PORT DB_DATABASE DB_USERNAME DB_PASSWORD SESSION_DRIVER SESSION_LIFETIME SESSION_ENCRYPT SESSION_PATH SESSION_DOMAIN BROADCAST_CONNECTION FILESYSTEM_DISK QUEUE_CONNECTION CACHE_STORE MEMCACHED_HOST REDIS_CLIENT REDIS_HOST REDIS_PASSWORD REDIS_PORT MAIL_MAILER MAIL_SCHEME MAIL_HOST MAIL_PORT MAIL_USERNAME MAIL_PASSWORD MAIL_FROM_ADDRESS MAIL_FROM_NAME AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION AWS_BUCKET AWS_USE_PATH_STYLE_ENDPOINT VITE_APP_NAME REVERB_APP_ID REVERB_APP_KEY REVERB_APP_SECRET REVERB_HOST REVERB_PORT REVERB_SCHEME VITE_REVERB_APP_KEY VITE_REVERB_HOST VITE_REVERB_PORT VITE_REVERB_SCHEME; do sed -i "/^$K=/d" .env 2>/dev/null || true; done
    - cat .env.cpanel >> .env
    # Fully disable realtime on production (clean, no WebSocket attempts)
    - sed -i '/^BROADCAST_CONNECTION=/d' .env
    - echo "BROADCAST_CONNECTION=log" >> .env
    - sed -i '/^VITE_ENABLE_ECHO=/d' .env
    - echo "VITE_ENABLE_ECHO=false" >> .env
    # Remove any Reverb vars to avoid leaking localhost defaults in built assets
    - sed -i '/^REVERB_/d' .env 2>/dev/null || true
    - sed -i '/^VITE_REVERB_/d' .env 2>/dev/null || true
    - composer install --optimize-autoloader --no-dev --no-interaction
    - npm install --production
    - rm -rf public/build
    - npm run build
    - chmod -R 775 storage
    - chmod -R 775 bootstrap/cache
    # Check if database credentials are set before running migrations
    - if grep -q "^DB_DATABASE=$" .env || grep -q "^DB_USERNAME=$" .env || grep -q "^DB_PASSWORD=$" .env; then echo "WARNING: Database credentials are not set. Please update DB_DATABASE, DB_USERNAME, and DB_PASSWORD in .env file before running migrations."; else php artisan migrate --force; fi
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

